:toc:
= jQAssistant APOC Plugin

The project provides the Neo4j APOC procedures and functions as http://jqassistant.org/[jQAssistant] plugin.

== Installation

=== Prerequisites

- Java 8 or higher
- jQAssistant 1.9.0 or higher

=== Maven

The plugin can be enabled in a Maven based project by adding it as a dependency to the jQAssistant Maven plugin:
[source, xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <version>1.10.0</version>
            <executions>
                <execution>
                    <id>default-cli</id>
                    <goals>
                        <goal>scan</goal>
                        <goal>analyze</goal>
                    </goals>
                </execution>
            </executions>
            <!-- The jqassistant-apoc-plugin goes here -->
            <dependencies>
                <dependency>
                    <groupId>org.jqassistant.contrib.plugin</groupId>
                    <artifactId>jqassistant-apoc-plugin</artifactId>
                    <version>1.10.0</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
----

=== Command Line Distribution

Download the shaded JAR file from https://search.maven.org/artifact/org.jqassistant.contrib.plugin/jqassistant-apoc-plugin[Maven Central] and put it into the `/plugins` folder of the distribution.

=== Verify Installation

Start the integrated server via Maven (```mvn jqassistant:server```) or CLI (```jqassistant server```) and execute the following query in the Neo4j browser:

----
CALL apoc.help('text')
----

The query shall return successfully and return a list of available procedures.

== Changelog

=== 1.12.0
* Upgraded to jQAssistant 1.12.0 and APOC 3.5.0.17

=== 1.10.0
* Upgraded to jQAssistant 1.10.0

=== 1.9.0
* Upgraded to jQAssistant 1.9.0 and APOC 3.5.0.15

=== 1.8.1

* Fixed jQAssistant startup failure related to JAXB

=== 1.8.0

* Initial Release
