:toc:
= jQAssistant APOC Plugin

The project provides the Neo4j APOC procedures and functions as http://jqassistant.org/[jQAssistant] plugin.

[NOTE]
====
This plugin is deprecated and no longer supported.
Please migrate to jQAssistant 2.1.0 which allows adding APOC directly as plugin for the embedded store:

.Neo4j v4.x
[source,yaml]
----
jqassistant:
  store:
    embedded:
      neo4j-plugins:
        - group-id: org.neo4j.procedure
          artifact-id: apoc
          version: 4.4.0.25
----

.Neo4j v5.x
[source,yaml]
----
jqassistant:
  store:
    embedded:
      neo4j-plugins:
        - group-id: org.neo4j.procedure
          artifact-id: apoc-core
          classifier: core
          version: 5.17.0
----
====

== Installation

=== Prerequisites

- Java 11 or higher
- jQAssistant 2.0.0 or higher

=== Maven

The plugin can be enabled in the configuration file `.jqassistant.yml`:
[source,yml]
..jqassistant.yml
----
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-apoc-plugin
      version: 2.0.0
----

=== Verify Installation

Start the integrated server via Maven (```mvn jqassistant:server```) or CLI (```jqassistant server```) and execute the following query in the Neo4j browser:

----
CALL apoc.help('text')
----

The query shall return successfully and return a list of available procedures.

== Changelog

=== 2.0.0
* Upgraded to jQAssistant 2.0.0 and APOC 4.4.0.16
* Changed Maven coordinates to `org.jqassistant.plugin:jqassistant-apoc-plugin`

=== 1.12.0
* Upgraded to jQAssistant 1.12.0 and APOC 3.5.0.17

=== 1.10.0
* Upgraded to jQAssistant 1.10.0

=== 1.9.0
* Upgraded to jQAssistant 1.9.0 and APOC 3.5.0.15

=== 1.8.1

* Fixed jQAssistant startup failure related to JAXB

=== 1.8.0

* Initial Release
